import Foundation

/// Supported question formats generated by ExamAgent.
public enum ExamQuestionFormat: String, CaseIterable, Sendable {
    case mcq = "MCQ"
    case trueFalse = "True/False"
    case shortAnswer = "Short Answer"
    case essay = "Essay"
    case conceptComparison = "Concept Comparison"
    case oralQuestions = "Oral Questions"
}

/// Allowed ethical labels for generated exam questions.
public enum ExamQuestionAllowedLabel: String, CaseIterable, Sendable {
    case practiceQuestion = "Practice Question"
    case professorEmphasizedTopic = "Professor-Emphasized Topic"
    case importantReviewTopic = "Important Review Topic"
}

/// Strategic exam preparation analyst and practice question generator.
/// Enforces Section 24 Truth Standards: Never guarantees exam questions.
public final class ExamAgent: Agent, @unchecked Sendable {
    public let id: String = "agent.exam"
    public let name: String = "Exam Agent"
    public let description: String = "Tactical exam preparation analyst estimating high-probability review topics and generating practice question simulations."
    public let iconName: String = "doc.badge.gearshape.fill"
    public var status: AgentStatus = .ready

    public let capabilities: [AgentCapability] = [
        AgentCapability(id: "practice_questions", name: "Practice Questions", description: "Generates review questions strictly labeled as Practice Question, Professor-Emphasized Topic, or Important Review Topic."),
        AgentCapability(id: "mock_simulation", name: "Mock Exam Simulation", description: "Simulates timed midterm and final exam questions across MCQ, True/False, Short Answer, Essay, Concept Comparison, and Oral formats."),
        AgentCapability(id: "concept_comparison", name: "Comparative Essay Prompts", description: "Generates analytical prompts comparing core theorists and methodologies.")
    ]

    private let router: AIRouterProtocol

    public init(router: AIRouterProtocol) {
        self.router = router
    }

    public func execute(task: String, context: [String: String]) async throws -> String {
        let request = AIRequest(
            prompt: task,
            systemInstruction: "Sen Exam Agent'sın. Sınav hazırlığı için alıştırma soruları üret. Asla kesin sınav sorusu garantisi verme. Yalnızca izin verilen etiketleri kullan: 'Practice Question', 'Professor-Emphasized Topic', 'Important Review Topic'.",
            contextData: context
        )
        let response = try await router.execute(request: request)
        return response.content
    }

    /// Generates practice questions across multiple formats with strict truth-standard labeling.
    /// Sourced from course materials first.
    public func generatePracticeQuestions(
        courseName: String,
        emphasisItems: [ProfessorEmphasis] = [],
        courseNotesSnippet: String? = nil,
        format: ExamQuestionFormat = .mcq,
        questionCount: Int = 5,
        courseId: UUID? = nil
    ) async throws -> String {
        var materialContext = ""
        if let notes = courseNotesSnippet, !notes.isEmpty {
            materialContext += "KAYNAK DERS MATERYALLERİ:\n\(notes.prefix(1200))\n\n"
        }
        if !emphasisItems.isEmpty {
            materialContext += "HOCANIN DERSTE VURGULADIĞI KONULAR:\n" + emphasisItems.prefix(4).map {
                "[\($0.classification.title)]: \($0.exactSourceSnippet)"
            }.joined(separator: "\n")
        }

        let prompt = """
        DERS: \(courseName)
        SORU FORMATI: \(format.rawValue)
        SORU SAYISI: \(questionCount)

        \(materialContext)

        Lütfen öncelikle verilen ders materyallerini ve hoca vurgularını temel alarak \(questionCount) adet soru hazırla.
        ZORUNLU KURALLAR:
        1. Her soruyu YALNIZCA şu üç etiketten biriyle etiketle:
           - [Practice Question]
           - [Professor-Emphasized Topic]
           - [Important Review Topic]
        2. ASLA 'kesin çıkacak soru' veya 'sınav garantili' gibi yanıltıcı ifadeler kullanma.
        3. Format: \(format.rawValue) gerekliliklerine uygun şekilde yapılandır (MCQ için 4 seçenek, Essay için puanlama kriteri, Oral için sözlü sınav cevap anahtarı).
        4. Her soru için ders kaynaklı açıklayıcı çözüm anahtarı sağla.
        """

        let request = AIRequest(
            prompt: prompt,
            systemInstruction: "Sen AcademicOS Sınav Hazırlık asistanısın. Gerçekçi, akademik derinliği olan ve dürüst etiketlenmiş alıştırma soruları oluştur.",
            courseId: courseId
        )

        let response = try await router.execute(request: request)
        return response.content
    }
}
